item {
    name: "Bacterial",
    id: 1,
    display_name: "Bacterial"
}
item {
    name: "Downy_mildew_on_lettuce",
    id: 2,
    display_name: "Downy_mildew_on_lettuce"
}
item {
    name: "Powdery_mildew_on_lettuce",
    id: 3,
    display_name: "Powdery_mildew_on_lettuce"
}
item {
    name: "Septoria_Blight_on_lettuce",
    id: 4,
    display_name: "Septoria_Blight_on_lettuce"
}
item {
    name: "Viral",
    id: 5,
    display_name: "Viral"
}
item {
    name: "Wilt_and_leaf_blight_on_lettuce",
    id: 6,
    display_name: "Wilt_and_leaf_blight_on_lettuce"
}
item {
    name: "healthy",
    id: 7,
    display_name: "healthy"
}
